version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: seplag_root
      POSTGRES_PASSWORD: seplag_password
      POSTGRES_DB: seplag
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console UI
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_admin
    command: server /data --console-address ":9001"

  app:
    build:
      context: .         # Usa o Dockerfile da raiz do projeto
      dockerfile: Dockerfile
    container_name: springboot-app
    depends_on:
      - postgres
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/seplag
      SPRING_DATASOURCE_USERNAME: seplag_root
      SPRING_DATASOURCE_PASSWORD: seplag_password
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minio_admin
      MINIO_SECRET_KEY: minio_admin
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data:
  minio_data:
